# -*- coding: utf-8 -*-
"""GROUP 3 - PORTFOLIO OPTIMIZATION - 5 YEARS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gwY3iVW89g92MZmnHydj8IBit5iHcxPA
"""

# Import thư viện
import pandas as pd
import numpy as np
import seaborn as sb
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.linear_model import Lasso, Ridge, ElasticNet, LinearRegression
from sklearn.multioutput import MultiOutputRegressor
from sklearn.cluster import AffinityPropagation
from sklearn.covariance import GraphicalLassoCV
from sklearn.manifold import MDS
from statsmodels.tsa.stattools import adfuller
from itertools import combinations
import networkx as nx

"""#**PRE-PROCESSING**

##**Đọc dữ liệu và tiền xử lý**
"""

!pip install -U vnstock

"""**TECHNOLOGY**"""

from vnstock import Vnstock
stock = Vnstock().stock(symbol='FPT', source='VCI')
FPT = stock.quote.history(symbol='FPT', start='2020-01-01', end='2025-04-30',
interval='1D')
FPT

from vnstock import Vnstock
stock = Vnstock().stock(symbol='ELC', source='VCI')
ELC = stock.quote.history(symbol='ELC', start='2020-01-01', end='2025-04-30',
interval='1D')
ELC

from vnstock import Vnstock
stock = Vnstock().stock(symbol='SGT', source='VCI')
SGT = stock.quote.history(symbol='SGT', start='2020-01-01', end='2025-04-30',
interval='1D')
SGT

"""**LOGISTIC**"""

from vnstock import Vnstock
stock = Vnstock().stock(symbol='PDN', source='VCI')
PDN = stock.quote.history(symbol='PDN', start='2020-01-01', end='2025-04-30',
interval='1D')
PDN

from vnstock import Vnstock
stock = Vnstock().stock(symbol='HAH', source='VCI')
HAH = stock.quote.history(symbol='HAH', start='2020-01-01', end='2025-04-30',
interval='1D')
HAH

from vnstock import Vnstock
stock = Vnstock().stock(symbol='GMD', source='VCI')
GMD = stock.quote.history(symbol='GMD', start='2020-01-01', end='2025-04-30',
interval='1D')
GMD

"""**REAL ESTATE**"""

from vnstock import Vnstock
stock = Vnstock().stock(symbol='DXG', source='VCI')
DXG = stock.quote.history(symbol='DXG', start='2020-01-01', end='2025-04-30',
interval='1D')
DXG

from vnstock import Vnstock
stock = Vnstock().stock(symbol='VHM', source='VCI')
VHM = stock.quote.history(symbol='VHM', start='2020-01-01', end='2025-04-30',
interval='1D')
VHM

from vnstock import Vnstock
stock = Vnstock().stock(symbol='D2D', source='VCI')
D2D = stock.quote.history(symbol='D2D', start='2020-01-01', end='2025-04-30',
interval='1D')
D2D

"""**RETAILS**"""

from vnstock import Vnstock
stock = Vnstock().stock(symbol='MWG', source='VCI')
MWG = stock.quote.history(symbol='MWG', start='2020-01-01', end='2025-04-30',
interval='1D')
MWG

from vnstock import Vnstock
stock = Vnstock().stock(symbol='PNJ', source='VCI')
PNJ = stock.quote.history(symbol='PNJ', start='2020-01-01', end='2025-04-30',
interval='1D')
PNJ

from vnstock import Vnstock
stock = Vnstock().stock(symbol='MSN', source='VCI')
MSN = stock.quote.history(symbol='MSN', start='2020-01-01', end='2025-04-30',
interval='1D')
MSN

"""**BANKING**"""

from vnstock import Vnstock
stock = Vnstock().stock(symbol='TCB', source='VCI')
TCB = stock.quote.history(symbol='TCB', start='2020-01-01', end='2025-04-30',
interval='1D')
TCB

from vnstock import Vnstock
stock = Vnstock().stock(symbol='STB', source='VCI')
STB = stock.quote.history(symbol='STB', start='2020-01-01', end='2025-04-30',
interval='1D')
STB

from vnstock import Vnstock
stock = Vnstock().stock(symbol='LPB', source='VCI')
LPB = stock.quote.history(symbol='LPB', start='2020-01-01', end='2025-04-30',
interval='1D')
LPB

import pandas as pd

# Danh sách mã cổ phiếu
tickers = ["FPT","ELC","SGT","PDN","HAH","GMD","DXG","VHM","D2D","MWG","PNJ","MSN","TCB","STB","LPB"]


# Khởi tạo DataFrame
merged_df = None

for ticker in tickers:
    # Đọc DataFrame hiện tại (giả sử các DataFrame đã tồn tại)
    df = globals()[ticker]  # Lấy DataFrame dựa trên tên biến

    # Đổi tên cột 'close' thành tên mã cổ phiếu
    df = df.rename(columns={'close': ticker})

    # Giữ lại cột 'time' và cột giá mã cổ phiếu
    df = df[['time', ticker]]

    # Merge vào DataFrame tổng
    if merged_df is None:
        merged_df = df
    else:
        merged_df = pd.merge(merged_df, df, on='time', how='outer')

# Sắp xếp theo cột 'time'
data_demo = merged_df.sort_values('time').reset_index(drop=True)
# Kết quả là merged_df chứa giá đóng cửa của tất cả mã theo ngày
data_demo

# Định nghĩa danh sách mã cổ phiếu theo ngành
sectors = {
    "Technology": ["FPT", "ELC","SGT"],
    "Logistic": ["PDN", "HAH","GMD"],
    "Real Estate": ["DXG", "VHM","D2D"],
    "Retails": ["MWG", "PNJ", "MSN"],
    "Banking": ["TCB", "STB","LPB"],
}

# Tính giá cổ phiếu ngành bằng trung bình giá cổ phiếu của các mã trong ngành
sector_prices = {}
for sector, stocks in sectors.items():
    sector_prices[sector] = data_demo[stocks].mean(axis=1)

# Chuyển đổi kết quả thành DataFrame
df = pd.DataFrame(sector_prices)
df['Date'] = data_demo['time']
df['Date'] = pd.to_datetime(df['Date'], format='%d-%m-%y')
df = df.set_index('Date')
df = df.sort_index()
df

"""##**Dữ liệu thiếu**"""

from collections.abc import Sequence
import matplotlib.pyplot as plt

# Tính số lượng giá trị thiếu
missing_values = df.isnull().sum()
missing_values = missing_values.sort_values(ascending=False)

# Vẽ biểu đồ cột
ax = missing_values.plot(kind='bar', figsize=(15, 5), color='skyblue')
plt.title('Missing Values')
plt.ylabel('Số lượng thiếu')
plt.xticks(rotation=45)

# Bổ sung giá trị trên từng cột
for i, value in enumerate(missing_values):
    if value > 0:
        ax.text(i, value + 1, str(value), ha='center', va='bottom', fontsize=9)

plt.tight_layout()
plt.show()

df.dropna(inplace=True)
df

"""#**RETURN AND RISK ANALYSIS**"""

import matplotlib.pyplot as plt
import matplotlib.dates as mdates

industries = ["Technology", "Logistic", "Real Estate", "Retails", "Banking"]

for industry in industries:
    plt.figure(figsize=(12, 6))
    plt.plot(df.index, df[industry], label="Actual Prices", color="blue")
    plt.xlabel("Year")
    plt.ylabel("Price")
    plt.title(f"{industry} Price Over Time")
    plt.grid()
    ax = plt.gca()
    ax.xaxis.set_major_locator(mdates.YearLocator(1))
    plt.xticks(rotation=45)
    plt.legend()
    plt.show()

"""##**Tính toán lợi nhuận**"""

df_return = df.pct_change().dropna()

# Lợi nhuận trung bình hàng ngày
mean_values = df_return.mean()

# Hàng tháng
monthly_mean = (1 + mean_values)**21 - 1

# Hàng năm
annualized_mean = (1 + mean_values)**250 - 1

# Lợi nhuận tích lũy
compound_return = (df_return + 1).prod() - 1

summary_returns = pd.DataFrame({
    'Daily Mean': mean_values,
    'Monthly Mean': monthly_mean,
    'Annualized Mean': annualized_mean,
    'Cumulative Return': compound_return
})
print(summary_returns)

industries = ["Technology", "Logistic", "Real Estate", "Retails", "Banking"]
summary_returns = pd.DataFrame({
    'Daily Mean': mean_values[industries],
    'Monthly Mean': monthly_mean[industries],
    'Annualized Mean': annualized_mean[industries],
    'Cumulative Return': compound_return[industries]
})
print(summary_returns)

"""##**Ước lượng độ biến động**"""

std_daily = df_return.std()
variance = df_return.var()
volatility = variance.pow(0.5)

industries = ["Technology", "Logistic", "Real Estate", "Retails", "Banking"]
risk_df = pd.DataFrame({
    'Daily Std': std_daily[industries],
    'Variance': variance[industries],
    'Volatility': volatility[industries]
})
risk_df.sort_values(by = 'Volatility', ascending = False)

semideviation = df_return[df_return < 0].std(ddof=0)
industries = ["Technology", "Logistic", "Real Estate", "Retails", "Banking"]
semideviation[industries].sort_values(ascending = False)

annualized_volatility = df_return.std()*np.sqrt(250)
industries = ["Technology", "Logistic", "Real Estate", "Retails", "Banking"]
annualized_volatility = annualized_volatility[industries]
print(annualized_volatility.sort_values(ascending=False))

n_days = len(df_return)
annualized_return = (df_return + 1).prod()**(250 / n_days) - 1
industries = ["Technology", "Logistic", "Real Estate", "Retails", "Banking"]
annualized_return = annualized_return[industries]
print(annualized_return.sort_values(ascending=False))

#RTRR đo lường mức lợi nhuận nhận được cho mỗi đơn vị rủi ro.
rtrr = annualized_return / annualized_volatility
print(rtrr.sort_values(ascending=False))
rtrr_df = pd.DataFrame ({
    'Annualized Return': annualized_return,
    'Annualized Volatility': annualized_volatility,
    'RTRR': rtrr
})
rtrr_df.sort_values(by = 'RTRR', ascending = False)

#ggdrive
import pandas as pd

from google.colab import drive
import os

drive.mount('/content/drive')
WORKING_DIR = '/content/drive/MyDrive/GROUP ĐẠI HỌC/ADVANCED INVESTMENT ANALYSIS/01_Investment 2025-T7/03_Code/1.1 Analysing return'

if not os.path.exists(WORKING_DIR):
    os.makedirs(WORKING_DIR)

os.chdir(WORKING_DIR)
print("Current working directory:", os.getcwd())

import importlib.util
import os

# Define the full path to the file using an absolute path
file_path = "/content/drive/MyDrive/GROUP ĐẠI HỌC/ADVANCED INVESTMENT ANALYSIS/01_Investment 2025-T7/03_Code/1.1 Analysing return/edhec_risk_kit.py"

# Load the module
spec = importlib.util.spec_from_file_location("edhec_risk_kit", file_path)
erk = importlib.util.module_from_spec(spec)
spec.loader.exec_module(erk)

# List available functions
print(dir(erk))

industries = ["Technology", "Logistic", "Real Estate", "Retails", "Banking"]
var_historic_value = erk.var_historic(df_return)
var_historic_value[industries].sort_values(ascending = False)

var_gaussian_value = erk.var_gaussian(df_return)
var_gaussian_value[industries].sort_values(ascending = False)

# Cornish-Fisher just adjusts z-score in regard to skeweness and kurtosis
var_list = [erk.var_gaussian(df_return[industries]), erk.var_gaussian(df_return[industries], modified=True), erk.var_historic(df_return[industries])]
comparison = pd.concat(var_list, axis=1)

comparison.columns = ["Gaussian", 'Cornish-Fisher', 'Historic']

from tabulate import tabulate
comparison_rounded = comparison.round(6)
print(comparison_rounded.sort_values(by = 'Gaussian', ascending = False))

comparison.plot.bar(title="5 SECTORS: VaR").legend(bbox_to_anchor=(1.05, 0.5), loc='center left', borderaxespad=0.)

cvar_historic_value = erk.cvar_historic(df_return[industries]).sort_values(ascending = False)
print(cvar_historic_value)

ax = cvar_historic_value.plot.bar(figsize=(12, 8), title="CVaR for Each Sector")

for idx, value in enumerate(cvar_historic_value):
    ax.annotate(f"{value:.4f}",  # Hiển thị số liệu với 4 chữ số thập phân
                xy=(idx, value),  # Tọa độ trên biểu đồ
                xytext=(0, 5),  # Khoảng cách so với đầu cột (trục y)
                textcoords="offset points",
                ha="center", va="bottom", fontsize=10)

"""##**Sharpe Ratio & Risk-Adjusted Metrics**"""

# Sharpe Ratio:
riskfree_rate = 0.027
excess_return = annualized_return - riskfree_rate

sharpe_ratio = excess_return / annualized_volatility
sharpe_ratio = sharpe_ratio.sort_values(ascending=False)
print(sharpe_ratio)

ax = sharpe_ratio.plot.bar(figsize=(18, 6), title="Sharpe Ratio")
for idx, value in enumerate(sharpe_ratio):
    ax.annotate(f"{value:.4f}",  # Hiển thị số liệu với 4 chữ số thập phân
                xy=(idx, value),  # Tọa độ trên biểu đồ
                xytext=(0, 5),  # Khoảng cách so với đầu cột (trục y)
                textcoords="offset points",
                color = 'black',
                ha="center", va="center", fontsize=10)

"""##**Max Drawdown Calculation**"""

import matplotlib.pyplot as plt

# 5 ngành cần phân tích
industries = ["Technology", "Logistic", "Real Estate", "Retails", "Banking"]

# Tạo Wealth Index ban đầu cho mỗi ngành
wealth_index = (1 + df_return).cumprod() * 1000  # Giá trị ban đầu là 1000, hoặc giá trị tùy ý

# Tính Previous Peaks (đỉnh cao trước đó)
previous_peaks = wealth_index.cummax()

# Vẽ biểu đồ Previous Peaks cho từng ngành
for industry in industries:
    plt.figure(figsize=(12, 6))
    plt.plot(previous_peaks.index, previous_peaks[industry], label=f"Previous Peaks - {industry}", color='green', linewidth=2)
    plt.title(f"Previous Peaks for {industry}")
    plt.xlabel("Time")
    plt.ylabel("Previous Peaks")
    plt.legend()
    plt.grid(True)
    plt.show()

# Tính Drawdown cho các ngành
drawdown = (wealth_index - previous_peaks) / previous_peaks

# Vẽ biểu đồ Drawdown cho từng ngành
for industry in industries:
    plt.figure(figsize=(12, 6))
    plt.plot(drawdown.index, drawdown[industry], label=f"Drawdown - {industry}", color='crimson', linewidth=2)
    plt.title(f"Drawdown for {industry}")
    plt.xlabel("Time")
    plt.ylabel("Drawdown")
    plt.legend()
    plt.grid(True)
    plt.show()

# Danh sách 5 ngành cần phân tích
industries = ["Technology", "Logistic", "Real Estate", "Retails", "Banking"]

# Tính Drawdown cho từng ngành
drawdown = (wealth_index - previous_peaks) / previous_peaks

# Tính Minimum Drawdown cho từng ngành
minimum_drawdown = drawdown[industries].min()  # Chỉ tính cho 5 ngành

# Hiển thị Minimum Drawdown dưới dạng biểu đồ cột
plt.figure(figsize=(14, 6))
plt.bar(minimum_drawdown.index, minimum_drawdown.values, color='red', alpha=0.7)
plt.title("Minimum Drawdown for Each Industry")
plt.xlabel("Industry")
plt.ylabel("Minimum Drawdown")
plt.xticks(rotation=45)  # Xoay nhãn để dễ đọc
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

# Hiển thị kết quả bằng văn bản cho từng ngành
for industry, min_value in minimum_drawdown.items():
    print(f"Minimum Drawdown for {industry}: {round(min_value, 4)}")

def drawdown(return_series: pd.Series):
    wealth_index = 1000 * (1 + return_series).cumprod()
    previous_peaks = wealth_index.cummax()
    drawdowns = (wealth_index - previous_peaks) / previous_peaks
    return pd.DataFrame({
        'Wealth': wealth_index,
        'Peaks': previous_peaks,
        'Drawdown': drawdowns
    })

# Vẽ biểu đồ Wealth Index và Previous Peaks cho từng ngành
for industry in industries:
    plt.figure(figsize=(12, 7))

    # Sử dụng hàm drawdown để tính Wealth Index và Previous Peaks
    dd = drawdown(df_return[industry])

    # Vẽ Wealth Index và Previous Peaks
    dd[['Wealth', 'Peaks']].plot(figsize=(12, 7), color=['b', 'g'])

    # Thiết lập tiêu đề và các nhãn
    plt.title(f"Wealth Index and Previous Peaks for {industry}")
    plt.xlabel("Time")
    plt.ylabel("Value")
    plt.grid(True)
    plt.legend()
    plt.show()

"""#**FACTOR ANALYSIS AND MARKET MODELING**

##**Phân tích nhân tố dựa trên mô hình CAPM và Fama-French**
"""

import pandas as pd

# Đọc dữ liệu (nếu từ CSV)
total_mk = pd.read_excel("/content/drive/MyDrive/GROUP ĐẠI HỌC/ADVANCED INVESTMENT ANALYSIS/01_Investment 2025-T7/03_Code/1.1 Analysing return/Total Market Capitalization.xlsx")

# Chuyển cột 'date' thành DatetimeIndex
total_mk['time'] = pd.to_datetime(total_mk['time'])
total_mk = total_mk.set_index('time')

total_mk_d = total_mk.pct_change().dropna()
total_mk_d.index.name = "time"
total_mk_d

# Commented out IPython magic to ensure Python compatibility.
import edhec_risk_kit_201 as erk

# %load_ext autoreload
# %autoreload 2

total_mk_m = total_mk_d.resample('M').apply(erk.compound).to_period('M')
total_mk_m

# Đọc dữ liệu Fama-French 3-Factor theo tháng
fff = pd.read_excel('/content/drive/MyDrive/GROUP ĐẠI HỌC/ADVANCED INVESTMENT ANALYSIS/01_Investment 2025-T7/03_Code/1.1 Analysing return/Fama French 3 Factor.xlsx', sheet_name='Sheet1')
fff = fff.rename(columns={'time': 'Date'})
fff['Date'] = pd.to_datetime(fff['Date'])  # Đảm bảo Date là datetime
fff = fff.set_index('Date')
fff

import statsmodels.api as sm
import numpy as np
rf_series = fff.loc["2020":"2025-04", 'RF']  # Lấy RF dưới dạng Series
rf_series.index = rf_series.index.to_period("M")
total_mk_excess = total_mk_m.loc["2020":"2025-04"].squeeze() - rf_series
#total_mk_excess.index = pd.PeriodIndex(total_mk_excess.index, freq="M")
#total_mk_excess = total_mk_excess[(total_mk_excess.index >= pd.Period("2020-01", freq="M")) &
#                                  (total_mk_excess.index <= pd.Period("2025-01", freq="M"))]
#total_mk_excess = total_mk_excess[~total_mk_excess.index.duplicated(keep='first')]



mkt_excess = fff.loc["2020":"2025-04",['MKT-RF']]
exp_var = mkt_excess.copy()
exp_var["Constant"] = 1

print("Tháng có trong rf_series nhưng không có trong total_mk_m:", set(rf_series.index) - set(total_mk_m.index))
print("Tháng có trong total_mk_m nhưng không có trong rf_series:", set(total_mk_m.index) - set(rf_series.index))

print("rf_series index type after conversion:", type(rf_series.index))
print("total_mk_m index type:", type(total_mk_m.index))
print("Are indices exactly equal now?", total_mk_m.index.equals(rf_series.index))

total_mk_excess

print("total_mk_m index type:", type(total_mk_m.index))
print("rf_series index type:", type(rf_series.index))

print("total_mk_m index sample:", total_mk_m.index[:5])
print("rf_series index sample:", rf_series.index[:5])

a = pd.DataFrame({
    'Total Market Excess': total_mk_excess.squeeze(),
    'Total_mkt_m': total_mk_m.squeeze(),
    'rf_series': rf_series.squeeze()
})
a

exp_var

exp_var.index = exp_var.index.to_period("M")

print("total_mk_excess index:\n", total_mk_excess.index)
print("exp_var index:\n", exp_var.index)

lm = sm.OLS(total_mk_excess, exp_var).fit()
lm.summary()

"""**Giải thích điểm chuẩn CAPM**"""

fff.index = pd.to_datetime(fff.index)  # Convert to DatetimeIndex
fff.index = fff.index.to_period(freq="M")  # Now convert to PeriodIndex

exp_var["Value"] = fff.loc["2020":"2025-04", "hml"]
exp_var["Size"] = fff.loc["2020":"2025-04", "smb_factor"]
exp_var.head(10)

import statsmodels.api as sm
def regress(dependent_variable, explanatory_variables, alpha=True):
    """
    Runs a linear regression to decompose the dependent variable into the explanatory variables
    returns an object of type statsmodel's RegressionResults on which you can call
       .summary() to print a full summary
       .params for the coefficients
       .tvalues and .pvalues for the significance levels
       .rsquared_adj and .rsquared for quality of fit
    """
    if alpha:
        explanatory_variables = explanatory_variables.copy()
        explanatory_variables["Alpha"] = 1

    lm = sm.OLS(dependent_variable, explanatory_variables).fit()
    return lm

# Convert index to DatetimeIndex first if it's a generic Index
if not isinstance(mkt_excess.index, pd.DatetimeIndex):
    mkt_excess.index = pd.to_datetime(mkt_excess.index)

# Now convert to PeriodIndex
mkt_excess.index = mkt_excess.index.to_period(freq="M")

print("total_mk_excess index type:", type(total_mk_excess.index))
print("mkt_excess index type:", type(mkt_excess.index))

print("Are indices exactly equal?", total_mk_excess.index.equals(mkt_excess.index))

result = erk.regress(total_mk_excess, mkt_excess)
result_df = pd.DataFrame ({
    'Result params' : result.params,
    'Result tvalues' : result.tvalues,
    'Result pvalues' : result.pvalues,
    'Result rsquared_adj' : result.rsquared_adj,
    'Result rsquared' : result.rsquared
})
result_df

erk.regress(total_mk_excess, exp_var, alpha=False).summary()

df_return_d = df_return[industries].dropna()
#df_return_d.index.name = "time"
df_return_d.index = pd.to_datetime(df_return_d.index)
df_return_d

df_return_m = df_return_d.resample('ME').apply(erk.compound).to_period('M')
df_return_m

import statsmodels.api as sm
import edhec_risk_kit_206 as erk

fff = pd.read_excel('Fama French 3 Factor.xlsx', parse_dates=["time"])
fff.set_index("time", inplace=True)
fff.index = pd.to_datetime(fff.index)  # Ensure DatetimeIndex

def calcCAMP(startYear, endYear, industry, threeFactor=False):

    returnData = df_return_m[startYear:endYear]
    r = returnData[[industry]]
    r = r/100

    data_excess = r - fff.loc[startYear:endYear, ['RF']].values
    mkt_excess = fff.loc[startYear:endYear,['MKT-RF']]
    exp_var = mkt_excess.copy()
    exp_var["Constant"] = 1
    if threeFactor:
        exp_var["Size"] = fff.loc[startYear:endYear,['smb_factor']]
        exp_var["Value"] = fff.loc[startYear:endYear,['hml']]
    lm = sm.OLS(data_excess, exp_var).fit()
    return lm.params;

df_return_m.index = df_return_m.index.to_timestamp()
fff.index = pd.to_datetime(fff.index)  # Đảm bảo fff cũng dùng DatetimeIndex

params = calcCAMP("2020", "2024", "Retails", threeFactor=True)
print("Available keys in params:", params.index.tolist())  # Check column names

industryVals = {}

for col in df_return_m.columns:
    industryVals[col] = calcCAMP("2020", "2024", col)["MKT-RF"]

a = pd.DataFrame(industryVals.items(), columns=['Industry', 'CAPM']).sort_values("CAPM", ascending=False)
a

industryVals = {}

for col in df_return_m.columns:
    industryVals[col] = calcCAMP("2020", "2024", col, threeFactor=True)['Size']
pd.DataFrame(industryVals.items(), columns=['Industry', 'Size']).sort_values("Size", ascending=False)

industryVals = {}

for col in df_return_m.columns:
    industryVals[col] = calcCAMP("2020", "2024", col, threeFactor=True)['Value']
pd.DataFrame(industryVals.items(), columns=['Industry', 'Value']).sort_values("Value", ascending=False)

industryVals = {}

for col in df_return_m.columns:
    industryVals[col] = calcCAMP("2020", "2024", col, threeFactor=True)['MKT-RF']
pd.DataFrame(industryVals.items(), columns=['Industry', 'MKT-RF']).sort_values("MKT-RF", ascending=False)

industryVals = {}

for col in df_return_m.columns:
    industryVals[col] = calcCAMP("2020", "2024", col)["Constant"]
pd.DataFrame(industryVals.items(), columns=['Industry', 'Constant']).sort_values("Constant", ascending=False)

"""##**Comparing Equal-Weighted (EW) vs. Capitalization-Weighted (CW) Portfolios**"""

ew_weights = np.repeat(1 / len(df_return_m.columns), len(df_return_m.columns))
ew_return = df_return_m @ ew_weights

# Chọn 5 ngành để phân tích
sector_cols = ["Technology", "Logistic", "Real Estate", "Retails", "Banking"]
df_cap = df[sector_cols].copy()
df_cw_weight = df_cap.div(df_cap.sum(axis=1), axis=0)

# Chuẩn hóa lại thời gian index
df_cw_weight = df_cw_weight.resample('MS').last()
df_cw_weight = df_cw_weight.reindex(df_return_m.index)
cw_return = (df_return_m * df_cw_weight).sum(axis=1)

# Lợi nhuận EW
ew_weights = np.repeat(1 / len(sector_cols), len(sector_cols))
ew_return = df_return_m @ ew_weights

# So sánh biểu đồ tích lũy
(1 + ew_return).cumprod().plot(label='Equal-Weighted')
(1 + cw_return).cumprod().plot(label='Cap-Weighted')
plt.title("Hiệu suất tích lũy: EW vs CW")
plt.legend()
plt.grid(True)
plt.show()

def perf_stats(r):
    return pd.Series({
        "Mean": r.mean(),
        "Volatility": r.std(),
        "Sharpe": r.mean() / r.std()
    })

pd.DataFrame({
    "Equal-Weighted": perf_stats(ew_return),
    "Cap-Weighted": perf_stats(cw_return)
})

# Hoặc trọng số tại thời điểm gần nhất
last_month_weights = df_cw_weight.iloc[-1]
print("Trọng số đầu tư theo CW tại thời điểm gần nhất:")
last_month_weights.sort_values(ascending = False)

plt.figure (figsize = (14,4))
last_month_weights.sort_values(ascending = False).plot(kind ='bar', color = 'darkgreen', edgecolor = 'black')
plt.xlabel('Industries')
plt.title('Trọng số theo Cap Weight')
plt.tight_layout()
plt.show()

"""#**PORTFOLIO OPTIMIZATION STRATEGIES**

##**Xác định trọng số danh mục dựa trên hiệu suất rủi ro-lợi nhuận**
"""

#RTRR đo lường mức lợi nhuận nhận được cho mỗi đơn vị rủi ro.
rtrr = annualized_return / annualized_volatility
rtrr_df = pd.DataFrame ({
    'Annualized Return': annualized_return,
    'Annualized Volatility': annualized_volatility,
    'RTRR': rtrr
})
rtrr_df.sort_values(by = 'RTRR', ascending = False)

# Chuẩn hóa RTRR thành trọng số danh mục (tổng bằng 1)
rtrr_weights = rtrr / rtrr.sum()
print("Trọng số danh mục theo hiệu suất rủi ro-lợi nhuận:")
rtrr_weights.sort_values(ascending = False)

plt.figure(figsize = (14,4))
rtrr_weights.sort_values(ascending = False).plot(kind = 'bar', color = 'darkgreen', edgecolor = 'black')
plt.xlabel('Industries')
plt.title('Trọng số theo RTRR')
plt.tight_layout()
plt.xticks(rotation = 45)
plt.show()

"""##**Danh mục tối đa hóa Sharpe Ratio**"""

def annualize_rets(r, periods_per_year):
    """
    Tính lợi nhuận hàng năm hóa từ dữ liệu tỷ suất sinh lời
    r: DataFrame hoặc Series chứa tỷ suất sinh lời
    periods_per_year: Số kỳ trong một năm (250 cho dữ liệu hàng ngày)
    """
    compounded_growth = (1 + r).prod()  # Tăng trưởng tích lũy
    n_periods = r.shape[0]  # Số kỳ
    return compounded_growth**(periods_per_year / n_periods) - 1

# Tính lợi nhuận hàng năm hóa
annualized_returns = annualize_rets(df_return[["Technology", "Logistic", "Real Estate", "Retails", "Banking"]], 250)
print("Lợi nhuận hàng năm hóa:")
annualized_returns.sort_values(ascending = False)

l = ["Technology", "Logistic", "Real Estate", "Retails", "Banking"]
annualized_returns[l]

#Tính ma trận hiệp phương sai
cov_matrix = df_return.cov()
cov_matrix.loc[l, l]

# Portfolio correspond simply to an allocation of capital
# The weights correspond to the allocation
weights = np.repeat(1/5, 5)
weights

import numpy as np
def portfolio_return(weights, returns):
    """
    Tính lợi nhuận danh mục đầu tư
    weights: Trọng số của các tài sản (list hoặc numpy array)
    returns: Lợi nhuận kỳ vọng của các tài sản (list, numpy array hoặc pandas Series)
    """
    return np.dot(weights, returns)

def portfolio_return(weights, returns):
    """
    Tính lợi nhuận danh mục đầu tư
    weights: Trọng số của các tài sản (list hoặc numpy array)
    returns: Lợi nhuận kỳ vọng của các tài sản (list, numpy array hoặc pandas Series)
    """
    # Ensure weights and returns have the same length
    if len(weights) != len(returns):
        raise ValueError("Weights and returns must have the same length.")
    return np.dot(weights, returns)

l = ["Technology", "Logistic", "Real Estate", "Retails", "Banking"]
# weights should have the same length as the number of assets in l (5)
weights = np.repeat(1/len(l), len(l))

portfolio_return(weights, annualized_returns[l])

import numpy as np

def portfolio_vol(weights, cov_matrix):
    """
    Tính độ lệch chuẩn (volatility) của danh mục đầu tư
    weights: Trọng số của các tài sản (numpy array)
    cov_matrix: Ma trận hiệp phương sai (numpy array hoặc pandas DataFrame)
    """
    return np.sqrt(np.dot(weights.T, np.dot(cov_matrix, weights)))

portfolio_vol(weights, cov_matrix.loc[l, l])

import numpy as np
import pandas as pd
from scipy.optimize import minimize

# Các hàm cơ bản
def portfolio_return(weights, returns):
    """Tính lợi nhuận danh mục đầu tư."""
    return np.dot(weights, returns)

def portfolio_vol(weights, cov_matrix):
    """Tính độ biến động danh mục đầu tư."""
    return np.sqrt(np.dot(weights.T, np.dot(cov_matrix, weights)))

def minimize_vol(target_return, annualized_returns, cov_matrix):
    """
    Tìm trọng số tối ưu để đạt được độ biến động nhỏ nhất
    với lợi nhuận kỳ vọng mục tiêu.
    """
    n = annualized_returns.shape[0]
    init_guess = np.repeat(1/n, n)
    bounds = ((0.0, 1.0),) * n
    weights_sum_to_1 = {'type': 'eq', 'fun': lambda weights: np.sum(weights) - 1}
    return_is_target = {
        'type': 'eq',
        'args': (annualized_returns,),
        'fun': lambda weights, annualized_returns: portfolio_return(weights, annualized_returns) - target_return
    }
    result = minimize(portfolio_vol, init_guess,
                      args=(cov_matrix,), method="SLSQP",
                      constraints=(weights_sum_to_1, return_is_target),
                      bounds=bounds)
    return result.x

def optimal_weights(n_points, returns, cov_matrix):
    """Tìm các trọng số tối ưu cho nhiều mức lợi nhuận kỳ vọng."""
    target_returns = np.linspace(returns.min(), returns.max(), n_points)
    weights = [minimize_vol(tr, returns, cov_matrix) for tr in target_returns]
    return weights

def plot_ef(n_points, annualized_returns, cov_matrix):
    """
    Vẽ Efficient Frontier cho danh mục nhiều tài sản.
    """
    weights = optimal_weights(n_points, annualized_returns, cov_matrix)
    rets = [portfolio_return(w, annualized_returns) for w in weights]
    vols = [portfolio_vol(w, cov_matrix) for w in weights]
    ef = pd.DataFrame({"Returns": rets, "Volatility": vols})
    return ef.plot.line(x="Volatility", y="Returns", style='.-')

l = ["Technology", "Logistic", "Real Estate", "Retails", "Banking"]
plot_ef(25, annualized_returns[l], cov_matrix.loc[l,l]);

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

def plot_ef(n_points, er, cov, style='.-', show_cml=False, riskfree_rate=0.0, show_ew=False, show_gmv=False):
    """
    Vẽ Efficient Frontier với tùy chọn thêm Capital Market Line (CML), Equal-Weighted (EW) Portfolio,
    Global Minimum Variance (GMV) Portfolio.

    Parameters:
    - n_points: Số điểm trên Efficient Frontier.
    - er: Lợi nhuận kỳ vọng (expected returns) của các tài sản.
    - cov: Ma trận hiệp phương sai.
    - style: Kiểu đường đồ thị (ví dụ: '.-', 'x-', v.v.).
    - show_cml: Hiển thị Capital Market Line (CML) nếu True.
    - riskfree_rate: Lãi suất phi rủi ro để tính CML.
    - show_ew: Hiển thị danh mục Equal-Weighted nếu True.
    - show_gmv: Hiển thị danh mục Global Minimum Variance nếu True.
    """
    # Tìm trọng số tối ưu trên Efficient Frontier
    weights = optimal_weights(n_points, er, cov)
    rets = [portfolio_return(w, er) for w in weights]
    vols = [portfolio_vol(w, cov) for w in weights]

    # Tạo DataFrame chứa kết quả
    ef = pd.DataFrame({"Returns": rets, "Volatility": vols})

    # Vẽ Efficient Frontier
    ax = ef.plot.line(x="Volatility", y="Returns", style=style, figsize=(10, 6), title="Efficient Frontier")

    # Nếu hiển thị Capital Market Line
    if show_cml:
        sharpe_ratios = (ef["Returns"] - riskfree_rate) / ef["Volatility"]
        max_sharpe_idx = sharpe_ratios.idxmax()
        max_sharpe_ret = ef.loc[max_sharpe_idx, "Returns"]
        max_sharpe_vol = ef.loc[max_sharpe_idx, "Volatility"]

        # Vẽ đường CML
        cml_x = [0, max_sharpe_vol]
        cml_y = [riskfree_rate, max_sharpe_ret]
        ax.plot(cml_x, cml_y, color="green", linestyle="--", label="Capital Market Line (CML)")
        ax.scatter(max_sharpe_vol, max_sharpe_ret, color="red", label="Tangency Portfolio")

    # Nếu hiển thị danh mục Equal-Weighted
    if show_ew:
        n = er.shape[0]
        w_ew = np.repeat(1/n, n)
        r_ew = portfolio_return(w_ew, er)
        vol_ew = portfolio_vol(w_ew, cov)
        ax.plot([vol_ew], [r_ew], color='goldenrod', marker='o', markersize=10, label="Equal-Weighted Portfolio")

    # Nếu hiển thị GMV Portfolio
    if show_gmv:
        n = er.shape[0]
        jitter = 1e-6
        cov += np.eye(n) * jitter
        inv_cov = np.linalg.inv(cov)
        ones = np.ones(n)
        w_gmv = inv_cov @ ones / (ones.T @ inv_cov @ ones)
        r_gmv = portfolio_return(w_gmv, er)
        vol_gmv = portfolio_vol(w_gmv, cov)
        ax.plot([vol_gmv], [r_gmv], color='blue', marker='o', markersize=10, label="GMV Portfolio")

    ax.legend()
    return ax

plot_ef(25, annualized_returns[l], cov_matrix.loc[l,l], style='.-', show_cml=True, riskfree_rate=0.01, show_ew=True, show_gmv=True);

def display_weights_table(er, cov, riskfree_rate):
    """
    Hiển thị trọng số của các danh mục Tangency Portfolio, GMV Portfolio, và Equal-Weighted Portfolio dưới dạng bảng.

    Parameters:
    - er: Lợi nhuận kỳ vọng (expected returns) của các tài sản.
    - cov: Ma trận hiệp phương sai.
    - riskfree_rate: Lãi suất phi rủi ro.

    Returns:
    - DataFrame hiển thị trọng số các danh mục.
    """
    # Số lượng tài sản
    n = er.shape[0]

    # Trọng số Tangency Portfolio
    jitter = 1e-6
    cov += np.eye(n) * jitter  # Thêm jitter để đảm bảo ma trận khả nghịch
    inv_cov = np.linalg.inv(cov)
    ones = np.ones(n)
    w_gmv = inv_cov @ ones / (ones.T @ inv_cov @ ones)  # GMV weights
    sharpe_ratios = (er - riskfree_rate) / np.sqrt(np.diag(cov))
    tangency_weights = inv_cov @ (er - riskfree_rate) / (ones.T @ inv_cov @ (er - riskfree_rate))

    # Trọng số Equal-Weighted Portfolio
    w_ew = np.repeat(1/n, n)

    # Tạo bảng trọng số
    weights_df = pd.DataFrame({
        "Assets": er.index,
        "Tangency Portfolio": tangency_weights,
        "GMV Portfolio": w_gmv,
        "Equal-Weighted Portfolio": w_ew
    })

    return weights_df

ar = annualized_returns[["Technology", "Logistic", "Real Estate", "Retails", "Banking"]]
l = ["Technology", "Logistic", "Real Estate", "Retails", "Banking"]
ar = annualized_returns[l]
cm = cov_matrix.loc[l, l]

weights_table = display_weights_table(ar, cm, riskfree_rate=0.1)

weights_table

"""##**Kiểm tra hiệu suất của các danh mục đầu tư (backtest)**"""

def compound(r):
    """
    returns the result of compounding the set of returns in r
    """
    return np.expm1(np.log1p(r).sum())

df_return_m = df_return[industries].resample('M').apply(compound)

weights_table = display_weights_table(ar, cm, riskfree_rate=0.1)

tangency_weights = weights_table["Tangency Portfolio"].values
gmv_weights = weights_table["GMV Portfolio"].values
ew_weights = weights_table["Equal-Weighted Portfolio"].values

# Tính lợi nhuận hàng tháng cho mỗi danh mục
tangency_returns = df_return_m @ tangency_weights
gmv_returns = df_return_m @ gmv_weights
ew_returns = df_return_m @ ew_weights

# Tính wealth index (giá trị tài sản tích lũy ban đầu là 1000)
wealth_tangency = (1 + tangency_returns).cumprod() * 1000
wealth_gmv = (1 + gmv_returns).cumprod() * 1000
wealth_ew = (1 + ew_returns).cumprod() * 1000

plt.figure(figsize=(12, 6))
wealth_tangency.plot(label='Tangency Portfolio', linewidth=2)
wealth_gmv.plot(label='GMV Portfolio', linewidth=2)
wealth_ew.plot(label='Equal-Weighted Portfolio', linewidth=2)
plt.legend()
plt.title("So sánh hiệu suất các danh mục đầu tư")
plt.ylabel("Wealth Index")
plt.xlabel("Thời gian")
plt.grid(True)
plt.show()

def perf_stats(r):
    return pd.Series({
        "Mean Return": r.mean(),
        "Volatility": r.std(),
        "Sharpe": (r.mean() / r.std())
    })

# Tính hiệu suất cho mỗi danh mục
result_df = pd.DataFrame({
    "Tangency": perf_stats(tangency_returns),
    "GMV": perf_stats(gmv_returns),
    "Equal-Weighted": perf_stats(ew_returns)
}).T

result_df

industry_list = ["Technology", "Logistic", "Real Estate", "Retails", "Banking"]

# Lấy vốn hóa thời điểm gần nhất
last_cap = df_cap[industry_list].dropna().iloc[-1]

# Tính trọng số vốn hóa
cw_weights = last_cap / last_cap.sum()
print("Trọng số theo vốn hóa (Cap-Weighted):")
print(cw_weights.sort_values(ascending=False))

# Danh mục RTRR
rtrr_returns = df_return_m[industry_list] @ rtrr_weights

# Danh mục theo vốn hóa
cw_returns = df_return_m[industry_list] @ cw_weights

wealth_rtrr = (1 + rtrr_returns).cumprod() * 1000
wealth_cw = (1 + cw_returns).cumprod() * 1000

plt.figure(figsize=(14, 6))
wealth_tangency.plot(label='Tangency')
wealth_gmv.plot(label='GMV')
wealth_ew.plot(label='Equal-Weighted')
wealth_rtrr.plot(label='RTRR')
wealth_cw.plot(label='Cap-Weighted')

plt.title("So sánh hiệu suất 5 danh mục đầu tư")
plt.ylabel("Wealth Index")
plt.xlabel("Thời gian")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

all_portfolios = {
    "Tangency": tangency_returns,
    "GMV": gmv_returns,
    "Equal-Weighted": ew_returns,
    "RTRR": rtrr_returns,
    "Cap-Weighted": cw_returns
}

stats_df = pd.DataFrame({name: perf_stats(r) for name, r in all_portfolios.items()}).T
stats_df.style.format("{:.2%}")

"""#**ADVANCED PORTFOLIO DIVERSIFICATION AND RISK MANAGEMENT**

##**Xác định giới hạn của chiến lược đa dạng hóa**
"""

import seaborn as sns
import matplotlib.pyplot as plt

# Tính ma trận tương quan giữa các ngành
corr_matrix = df_return[industries].corr()

plt.figure(figsize=(10, 8))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title("Tương quan giữa các ngành")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

def diversification_effect(df_returns, industries):
    sharpe_ratios = []
    for i in range(2, len(industries)+1):
        sub_industries = industries[:i]
        sub_returns = df_returns[sub_industries]
        ew_weights = np.repeat(1/i, i)
        port_ret = sub_returns @ ew_weights
        sr = port_ret.mean() / port_ret.std()
        sharpe_ratios.append(sr)

    return sharpe_ratios

sharpe_by_industry_count = diversification_effect(df_return[industries], industries)

plt.figure(figsize=(10, 5))
plt.plot(range(2, len(industries)+1), sharpe_by_industry_count, marker='o')
plt.xlabel("Số ngành trong danh mục")
plt.ylabel("Sharpe Ratio")
plt.title("Sharpe Ratio theo số ngành đầu tư")
plt.grid(True)
plt.show()

"""##**Mô hình bảo hiểm danh mục để kiểm soát rủi ro**"""

def run_cppi(risky_r, safe_r=None, m=3, start=1000, floor=0.8, riskfree_rate=0.03, drawdown=None):
    """
    Run a backtest of the CPPI strategy, given a set of returns for the risky asset
    Returns a dictionary containing: Asset Value History, Risk Budget History, Risky Weight History
    """
    # set up the CPPI parameters
    dates = risky_r.index
    n_steps = len(dates)
    account_value = start
    floor_value = start*floor
    peak = account_value
    if isinstance(risky_r, pd.Series):
        risky_r = pd.DataFrame(risky_r, columns=["R"])

    if safe_r is None:
        safe_r = pd.DataFrame().reindex_like(risky_r)
        safe_r.values[:] = riskfree_rate/12 # fast way to set all values to a number
    # set up some DataFrames for saving intermediate values
    account_history = pd.DataFrame().reindex_like(risky_r)
    risky_w_history = pd.DataFrame().reindex_like(risky_r)
    cushion_history = pd.DataFrame().reindex_like(risky_r)
    floorval_history = pd.DataFrame().reindex_like(risky_r)
    peak_history = pd.DataFrame().reindex_like(risky_r)

    for step in range(n_steps):
        if drawdown is not None:
            peak = np.maximum(peak, account_value)
            floor_value = peak*(1-drawdown)
        cushion = (account_value - floor_value)/account_value
        risky_w = m*cushion
        risky_w = np.minimum(risky_w, 1)
        risky_w = np.maximum(risky_w, 0)
        safe_w = 1-risky_w
        risky_alloc = account_value*risky_w
        safe_alloc = account_value*safe_w
        # recompute the new account value at the end of this step
        account_value = risky_alloc*(1+risky_r.iloc[step]) + safe_alloc*(1+safe_r.iloc[step])
        # save the histories for analysis and plotting
        cushion_history.iloc[step] = cushion
        risky_w_history.iloc[step] = risky_w
        account_history.iloc[step] = account_value
        floorval_history.iloc[step] = floor_value
        peak_history.iloc[step] = peak
    risky_wealth = start*(1+risky_r).cumprod()
    backtest_result = {
        "Wealth": account_history,
        "Risky Wealth": risky_wealth,
        "Risk Budget": cushion_history,
        "Risky Allocation": risky_w_history,
        "m": m,
        "start": start,
        "floor": floor,
        "risky_r":risky_r,
        "safe_r": safe_r,
        "drawdown": drawdown,
        "peak": peak_history,
        "floor": floorval_history
    }
    return backtest_result

risky_r = df_return[["Technology", "Logistic", "Real Estate", "Retails", "Banking"]].dropna()

safe_r = pd.DataFrame().reindex_like(risky_r)
safe_r.values[:] = 0.027 / 12

# Chạy mô phỏng CPPI
results = run_cppi(
    risky_r=risky_r,
    safe_r=safe_r,
    m=3,
    start=1000,
    floor=0.8,
    riskfree_rate=0.03
)

import matplotlib.pyplot as plt

wealth = results["Wealth"]
risky_wealth = results["Risky Wealth"]

# Vẽ cho từng ngành
for col in wealth.columns:
    ax = wealth[col].plot(figsize=(12, 6), label='CPPI Wealth')
    risky_wealth[col].plot(ax=ax, style='--', label='Risky Asset')
    plt.axhline(y=800, color='r', linestyle='--', label='Floor Value')
    plt.title(f"CPPI Strategy vs Risky Wealth - {col}")
    plt.xlabel("Time")
    plt.ylabel("Portfolio Value")
    plt.legend()
    plt.grid(True)
    plt.show()

"""##**Mô phỏng lợi nhuận tài sản dựa trên giả định Random Walks**"""

import numpy as np
import pandas as pd

def gbm(n_years = 10, n_scenarios=1000, mu=0.07, sigma=0.15, steps_per_year=12, s_0=100.0):
    """
    Mô phỏng Geometric Brownian Motion (GBM) cho giá cổ phiếu
    """
    dt = 1/steps_per_year
    n_steps = int(n_years * steps_per_year)
    xi = np.random.normal(size=(n_steps, n_scenarios))
    rets = mu * dt + sigma * np.sqrt(dt) * xi
    prices = s_0 * (1 + rets).cumprod(axis=0)

    # Trả về DataFrame thay vì ndarray
    return pd.DataFrame(prices)

# Gọi lại và vẽ biểu đồ
gbm(n_years=10, n_scenarios=20, mu=0.07).plot(legend=False, figsize=(12,6))

"""##**Sử dụng Monte Carlo để đánh giá kịch bản danh mục đầu tư**"""

def show_gbm(n_scenarios, mu, sigma):
    """
    Draw the results of a stock price evolution under a Geometric Brownian Motion model
    """
    s_0=100
    prices = gbm(n_scenarios=n_scenarios, mu=mu, sigma=sigma, s_0=s_0)
    ax = prices.plot(legend=False, color="indianred", alpha = 0.5, linewidth=2, figsize=(12,5))
    ax.axhline(y=100, ls=":", color="black")
    # draw a dot at the origin
    ax.plot(0,s_0, marker='o',color='darkred', alpha=0.2)

import numpy as np
import pandas as pd

def gbm(n_years=10, n_scenarios=1000, mu=0.07, sigma=0.15, steps_per_year=12, s_0=100.0):
    """
    Mô phỏng Geometric Brownian Motion (GBM) cho giá cổ phiếu.

    Parameters:
    - n_years: Số năm mô phỏng.
    - n_scenarios: Số kịch bản để mô phỏng.
    - mu: Tỷ suất sinh lợi kỳ vọng hàng năm.
    - sigma: Độ biến động hàng năm.
    - steps_per_year: Số bước mô phỏng trong một năm.
    - s_0: Giá cổ phiếu ban đầu.

    Returns:
    - DataFrame chứa các kịch bản giá cổ phiếu theo thời gian.
    """
    dt = 1 / steps_per_year
    n_steps = int(n_years * steps_per_year)

    # Tạo ma trận số ngẫu nhiên
    xi = np.random.normal(size=(n_steps, n_scenarios))

    # Tính tỷ suất sinh lợi
    rets = mu * dt + sigma * np.sqrt(dt) * xi

    # Mô phỏng giá cổ phiếu
    prices = s_0 * (1 + rets).cumprod(axis=0)

    # Trả về DataFrame thay vì ndarray
    return pd.DataFrame(prices)

import ipywidgets as widgets
gbm_controls = widgets.interactive(show_gbm,
                                   n_scenarios=widgets.IntSlider(min=1, max=1000, step=1, value=1),
                                   mu=(0., +.2,.01),
                                   sigma=(0, .3, .01)
)

display(gbm_controls)

def gbm(n_years=10, n_scenarios=1000, mu=0.07, sigma=0.15, steps_per_year=12, s_0=100.0, prices=True):
    """
    Mô phỏng Geometric Brownian Motion (GBM) cho giá hoặc lợi nhuận cổ phiếu.

    Parameters:
    - n_years: Số năm mô phỏng.
    - n_scenarios: Số kịch bản mô phỏng.
    - mu: Tỷ suất sinh lợi kỳ vọng hàng năm.
    - sigma: Độ biến động hàng năm.
    - steps_per_year: Số bước mô phỏng trong một năm.
    - s_0: Giá cổ phiếu ban đầu.
    - prices: Nếu `True`, trả về giá cổ phiếu; nếu `False`, trả về lợi nhuận.

    Returns:
    - DataFrame chứa giá cổ phiếu hoặc lợi nhuận theo thời gian.
    """
    dt = 1 / steps_per_year
    n_steps = int(n_years * steps_per_year)

    # Tạo ma trận số ngẫu nhiên
    xi = np.random.normal(size=(n_steps, n_scenarios))

    # Tính tỷ suất sinh lợi
    rets = mu * dt + sigma * np.sqrt(dt) * xi

    if prices:
        prices = s_0 * (1 + rets).cumprod(axis=0)
        return pd.DataFrame(prices)
    else:
        return pd.DataFrame(rets)

def show_cppi(n_scenarios=50, mu=0.07, sigma=0.15, prices = True, m=3, floor=0., riskfree_rate=0.03, y_max=100):
    """
    Plot the results of a Monte Carlo Simulation of CPPI
    """
    start = 100
    sim_rets = gbm(n_scenarios=n_scenarios, mu=mu, sigma=sigma, prices=False, steps_per_year=12)
    risky_r = pd.DataFrame(sim_rets)
    # run the "back"-test
    btr = run_cppi(risky_r=pd.DataFrame(risky_r),riskfree_rate=riskfree_rate,m=m, start=start, floor=floor)
    wealth = btr["Wealth"]
    y_max=wealth.values.max()*y_max/100
    ax = wealth.plot(legend=False, alpha=0.3, color="indianred", figsize=(12, 6))
    ax.axhline(y=start, ls=":", color="black")
    ax.axhline(y=start*floor, ls="--", color="red")
    ax.set_ylim(top=y_max)

cppi_controls = widgets.interactive(show_cppi,
                                   n_scenarios=widgets.IntSlider(min=1, max=1000, step=5, value=50),
                                   mu=(0., +.2, .01),
                                   sigma=(0, .30, .05),
                                   floor=(0, 2, .1),
                                   m=(1, 5, .5),
                                   riskfree_rate=(0, .05, .01),
                                   y_max=widgets.IntSlider(min=0, max=100, step=1, value=100,
                                                          description="Zoom Y Axis")
)
display(cppi_controls)

"""#**EVALUATION AND STRATEGY COMPARISON**

##**So sánh các phương pháp phân bổ danh mục**
"""

plt.figure(figsize=(14, 6))
wealth_tangency.plot(label='Tangency')
wealth_gmv.plot(label='GMV')
wealth_ew.plot(label='Equal-Weighted')
wealth_rtrr.plot(label='RTRR')
wealth_cw.plot(label='Cap-Weighted')

plt.title("So sánh hiệu suất 5 danh mục đầu tư")
plt.ylabel("Wealth Index")
plt.xlabel("Thời gian")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

def perf_stats_v2(r, riskfree_rate=0.03):
    excess_ret = r - riskfree_rate / 12
    return pd.Series({
        "Mean Return": r.mean(),
        "Volatility": r.std(),
        "Sharpe": excess_ret.mean() / r.std(),
        "Sortino": excess_ret.mean() / erk.semideviation(r),
        "Max Drawdown": erk.drawdown(r).Drawdown.min(),
        "VaR (Gaussian)": erk.var_gaussian(r),
        "CVaR (Historic)": erk.cvar_historic(r)
    })

stats_df = pd.DataFrame({name: perf_stats_v2(r) for name, r in all_portfolios.items()}).T
display(stats_df.style.format("{:.2%}"))

"""##**Kiểm tra sự thay đổi trong phong cách đầu tư theo thời gian**"""

import matplotlib.pyplot as plt
from edhec_risk_kit_206 import style_analysis

industries = ["Technology", "Logistic", "Real Estate", "Retails", "Banking"]

fig, axes = plt.subplots(nrows=3, ncols=3, figsize=(20, 12))
axes = axes.flatten()

style_labels = None  # Sẽ lưu nhãn của các yếu tố

for i, industry in enumerate(industries):
    weights_df = []

    for date in df_return_m.index[12:]:
        sample = df_return_m.loc[:date].iloc[-12:]
        r = sample[industry]
        styles = sample.drop(columns=[industry])

        w = style_analysis(r, styles)
        w["Date"] = date
        weights_df.append(w)

    style_df = pd.DataFrame(weights_df)
    style_df.set_index("Date", inplace=True)

    style_df.plot(kind='area',
                  stacked=True,
                  ax=axes[i],
                  title=f"Style Drift - {industry}",
                  cmap='tab20',
                  legend=False)  # Tắt legend trong biểu đồ chính

    if style_labels is None:
        style_labels = style_df.columns

    axes[i].set_ylabel("Trọng số")
    axes[i].grid(True)

# Xóa subplot dư
for j in range(len(industries), len(axes)):
    fig.delaxes(axes[j])

plt.tight_layout()
plt.savefig("style_drift_main.png", dpi=300)
plt.show()
import matplotlib.patches as mpatches

# Tạo ảnh legend riêng
fig, ax = plt.subplots(figsize=(6, 4))
colors = plt.get_cmap('tab20').colors

patches = [mpatches.Patch(color=colors[i], label=label)
           for i, label in enumerate(style_labels)]

ax.legend(handles=patches, loc='center', frameon=False, ncol=2)
ax.axis('off')  # Tắt trục

plt.tight_layout()
plt.savefig("style_drift_legend.png", dpi=300)
plt.show()

"""#**MÃ CỔ PHIẾU**"""

stock = pd.DataFrame(data_demo)
stock.set_index('time', inplace=True)
stock.index = pd.to_datetime(stock.index)
stock.head()

stock_return = stock.pct_change().dropna()  # Tính tỷ lệ thay đổi phần trăm giữa các giá trị
stock_return.head()

# Giả sử returns là dữ liệu hàng ngày
n_days = len(stock_return)  # Số ngày trong dữ liệu

# Annualized return từ dữ liệu hàng ngày
annualized_return = (stock_return + 1).prod()**(250 / n_days) - 1
annualized_volatility = stock_return.std() * (12 ** 0.5)

rtrr = annualized_return / annualized_volatility
rtrr_weights = rtrr / rtrr.sum()

# Chuẩn hóa RTRR thành trọng số danh mục (tổng bằng 1)
print("Trọng số danh mục theo hiệu suất rủi ro-lợi nhuận:")
rtrr_weights.sort_values(ascending = False)

rtrr_weights.to_excel('rtrr weight.xlsx')

def annualize_rets(r, periods_per_year):
    """
    Tính lợi nhuận hàng năm hóa từ dữ liệu tỷ suất sinh lời
    r: DataFrame hoặc Series chứa tỷ suất sinh lời
    periods_per_year: Số kỳ trong một năm (250 cho dữ liệu hàng ngày)
    """
    compounded_growth = (1 + r).prod()  # Tăng trưởng tích lũy
    n_periods = r.shape[0]  # Số kỳ
    return compounded_growth**(periods_per_year / n_periods) - 1

# Tính lợi nhuận hàng năm hóa
annualized_returns = annualize_rets(stock_return, 250)
print("Lợi nhuận hàng năm hóa:")
print(annualized_returns)

l = ["FPT","ELC","SGT","PDN","HAH","GMD","DXG","VHM","D2D","MWG","PNJ","MSN","TCB","STB","LPB"]

annualized_returns[l].sort_values(ascending=False)

#Tính ma trận hiệp phương sai
cov_matrix = stock_return.cov()
cov_matrix.loc[l, l]

# Portfolio correspond simply to an allocation of capital
# The weights correspond to the allocation
weights = np.repeat(1/15, 15)
weights

import numpy as np
def portfolio_return(weights, returns):
    """
    Tính lợi nhuận danh mục đầu tư
    weights: Trọng số của các tài sản (list hoặc numpy array)
    returns: Lợi nhuận kỳ vọng của các tài sản (list, numpy array hoặc pandas Series)
    """
    return np.dot(weights, returns)

portfolio_return(weights, annualized_returns[l])

import numpy as np

def portfolio_vol(weights, cov_matrix):
    """
    Tính độ lệch chuẩn (volatility) của danh mục đầu tư
    weights: Trọng số của các tài sản (numpy array)
    cov_matrix: Ma trận hiệp phương sai (numpy array hoặc pandas DataFrame)
    """
    return np.sqrt(np.dot(weights.T, np.dot(cov_matrix, weights)))

portfolio_vol(weights, cov_matrix.loc[l, l])

import numpy as np
import pandas as pd
from scipy.optimize import minimize

# Các hàm cơ bản
def portfolio_return(weights, returns):
    """Tính lợi nhuận danh mục đầu tư."""
    return np.dot(weights, returns)

def portfolio_vol(weights, cov_matrix):
    """Tính độ biến động danh mục đầu tư."""
    return np.sqrt(np.dot(weights.T, np.dot(cov_matrix, weights)))

def minimize_vol(target_return, annualized_returns, cov_matrix):
    """
    Tìm trọng số tối ưu để đạt được độ biến động nhỏ nhất
    với lợi nhuận kỳ vọng mục tiêu.
    """
    n = annualized_returns.shape[0]
    init_guess = np.repeat(1/n, n)
    bounds = ((0.0, 1.0),) * n
    weights_sum_to_1 = {'type': 'eq', 'fun': lambda weights: np.sum(weights) - 1}
    return_is_target = {
        'type': 'eq',
        'args': (annualized_returns,),
        'fun': lambda weights, annualized_returns: portfolio_return(weights, annualized_returns) - target_return
    }
    result = minimize(portfolio_vol, init_guess,
                      args=(cov_matrix,), method="SLSQP",
                      constraints=(weights_sum_to_1, return_is_target),
                      bounds=bounds)
    return result.x

def optimal_weights(n_points, returns, cov_matrix):
    """Tìm các trọng số tối ưu cho nhiều mức lợi nhuận kỳ vọng."""
    target_returns = np.linspace(returns.min(), returns.max(), n_points)
    weights = [minimize_vol(tr, returns, cov_matrix) for tr in target_returns]
    return weights

def plot_ef(n_points, annualized_returns, cov_matrix):
    """
    Vẽ Efficient Frontier cho danh mục nhiều tài sản.
    """
    weights = optimal_weights(n_points, annualized_returns, cov_matrix)
    rets = [portfolio_return(w, annualized_returns) for w in weights]
    vols = [portfolio_vol(w, cov_matrix) for w in weights]
    ef = pd.DataFrame({"Returns": rets, "Volatility": vols})
    return ef.plot.line(x="Volatility", y="Returns", style='.-')

l = ["FPT","ELC","SGT","PDN","HAH","GMD","DXG","VHM","D2D","MWG","PNJ","MSN","TCB","STB","LPB"]
plot_ef(25, annualized_returns[l], cov_matrix.loc[l,l]);

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

def plot_ef(n_points, er, cov, style='.-', show_cml=False, riskfree_rate=0.0, show_ew=False, show_gmv=False, show_weights=True):
    """
    Vẽ Efficient Frontier với tùy chọn thêm Capital Market Line (CML), Equal-Weighted (EW) Portfolio,
    Global Minimum Variance (GMV) Portfolio, và hiển thị trọng số danh mục.

    Parameters:
    - n_points: Số điểm trên Efficient Frontier.
    - er: Lợi nhuận kỳ vọng (expected returns) của các tài sản.
    - cov: Ma trận hiệp phương sai.
    - style: Kiểu đường đồ thị (ví dụ: '.-', 'x-', v.v.).
    - show_cml: Hiển thị Capital Market Line (CML) nếu True.
    - riskfree_rate: Lãi suất phi rủi ro để tính CML.
    - show_ew: Hiển thị danh mục Equal-Weighted nếu True.
    - show_gmv: Hiển thị danh mục Global Minimum Variance nếu True.
    - show_weights: Hiển thị trọng số danh mục nếu True.
    """
    # Tìm trọng số tối ưu trên Efficient Frontier
    weights = optimal_weights(n_points, er, cov)
    rets = [portfolio_return(w, er) for w in weights]
    vols = [portfolio_vol(w, cov) for w in weights]

    # Tạo DataFrame chứa kết quả
    ef = pd.DataFrame({"Returns": rets, "Volatility": vols})

    # Vẽ Efficient Frontier
    ax = ef.plot.line(x="Volatility", y="Returns", style=style, figsize=(10, 6), title="Efficient Frontier")

    # Nếu hiển thị Capital Market Line
    if show_cml:
        sharpe_ratios = (ef["Returns"] - riskfree_rate) / ef["Volatility"]
        max_sharpe_idx = sharpe_ratios.idxmax()
        max_sharpe_ret = ef.loc[max_sharpe_idx, "Returns"]
        max_sharpe_vol = ef.loc[max_sharpe_idx, "Volatility"]
        w_tangency = weights[max_sharpe_idx]  # Trọng số Tangency Portfolio

        # Vẽ đường CML
        cml_x = [0, max_sharpe_vol]
        cml_y = [riskfree_rate, max_sharpe_ret]
        ax.plot(cml_x, cml_y, color="green", linestyle="--", label="Capital Market Line (CML)")
        ax.scatter(max_sharpe_vol, max_sharpe_ret, color="red", label="Tangency Portfolio")

        if show_weights:
            ax.text(max_sharpe_vol + 0.0002, max_sharpe_ret, f"Weights:\n{w_tangency.round(2)}", fontsize=8, color="red")

    # Nếu hiển thị danh mục Equal-Weighted
    if show_ew:
        n = er.shape[0]  # Số lượng tài sản
        w_ew = np.repeat(1/n, n)  # Trọng số đều nhau
        r_ew = portfolio_return(w_ew, er)  # Lợi nhuận EW
        vol_ew = portfolio_vol(w_ew, cov)  # Độ biến động EW

        # Vẽ danh mục Equal-Weighted
        ax.plot([vol_ew], [r_ew], color='goldenrod', marker='o', markersize=10, label="Equal-Weighted Portfolio")
        if show_weights:
            ax.text(vol_ew + 0.0002, r_ew, f"Weights:\n{w_ew.round(2)}", fontsize=8, color="goldenrod")

    # Nếu hiển thị GMV Portfolio
    if show_gmv:
        n = er.shape[0]
        jitter = 1e-6  # Giá trị jitter nhỏ
        cov += np.eye(n) * jitter  # Thêm jitter vào đường chéo ma trận
        inv_cov = np.linalg.inv(cov)  # Ma trận nghịch đảo
        ones = np.ones(n)
        w_gmv = inv_cov @ ones / (ones.T @ inv_cov @ ones)  # Trọng số GMV
        r_gmv = portfolio_return(w_gmv, er)  # Lợi nhuận GMV
        vol_gmv = portfolio_vol(w_gmv, cov)  # Độ biến động GMV

        # Vẽ điểm GMV Portfolio
        ax.plot([vol_gmv], [r_gmv], color='blue', marker='o', markersize=10, label="GMV Portfolio")
        if show_weights:
            ax.text(vol_gmv + 0.0002, r_gmv, f"Weights:\n{w_gmv.round(2)}", fontsize=8, color="blue")

    ax.legend()
    return ax

# Plot Efficient Frontier with EW Portfolio, CML, and GMV Portfolio
plot_ef(
    n_points=25,
    er=annualized_returns,
    cov=cov_matrix,
    style='x-',
    show_cml=True,
    riskfree_rate=0.0247,
    show_ew=True,
    show_gmv=True
)
plt.show()

def display_weights_table(er, cov, riskfree_rate):
    """
    Hiển thị trọng số của các danh mục Tangency Portfolio, GMV Portfolio, và Equal-Weighted Portfolio dưới dạng bảng.

    Parameters:
    - er: Lợi nhuận kỳ vọng (expected returns) của các tài sản.
    - cov: Ma trận hiệp phương sai.
    - riskfree_rate: Lãi suất phi rủi ro.

    Returns:
    - DataFrame hiển thị trọng số các danh mục.
    """
    # Số lượng tài sản
    n = er.shape[0]

    # Trọng số Tangency Portfolio
    jitter = 1e-6
    cov += np.eye(n) * jitter  # Thêm jitter để đảm bảo ma trận khả nghịch
    inv_cov = np.linalg.inv(cov)
    ones = np.ones(n)
    w_gmv = inv_cov @ ones / (ones.T @ inv_cov @ ones)  # GMV weights
    sharpe_ratios = (er - riskfree_rate) / np.sqrt(np.diag(cov))
    tangency_weights = inv_cov @ (er - riskfree_rate) / (ones.T @ inv_cov @ (er - riskfree_rate))

    # Trọng số Equal-Weighted Portfolio
    w_ew = np.repeat(1/n, n)

    # Tạo bảng trọng số
    weights_df = pd.DataFrame({
        "Assets": er.index,
        "Tangency Portfolio": tangency_weights,
        "GMV Portfolio": w_gmv,
        "Equal-Weighted Portfolio": w_ew
    })

    return weights_df

weights_table = display_weights_table(annualized_returns, cov_matrix, riskfree_rate=0.1)
weights_table.sort_values('GMV Portfolio', ascending=False)

import pandas as pd

# Chuyển giá trị âm thành 0
weights_table.iloc[:, 1:] = weights_table.iloc[:, 1:].clip(lower=0)

# Chuẩn hóa từng loại portfolio sao cho tổng = 1
for col in weights_table.columns[1:]:  # Bỏ qua cột 'Assets'
    weights_table[col] = weights_table[col] / weights_table[col].sum()

weights_table.sort_values('GMV Portfolio', ascending = False)

